#!/usr/bin/env bash


################################################################################
### Head: Note
##

## * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/project/bin/install.sh

##
### Tail: Note
################################################################################


################################################################################
### Head: Init
##

THE_BASE_DIR_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
THE_BASE_DIR_PATH="$THE_BASE_DIR_PATH/ext"
source "$THE_BASE_DIR_PATH/init.sh"
source "$THE_SYS_EXT_DIR_PATH/init.sh"

##
### Tail: Init
################################################################################


################################################################################
### Head: Theme
##


#source "$THE_SYS_PROFILE_DIR_PATH/default/theme.sh"
#source "$THE_SYS_PROFILE_DIR_PATH/main/theme.sh"
source "$THE_SYS_PROFILE_DIR_PATH/nord_aurora/theme.sh"


##
### Tail: Theme
################################################################################


################################################################################
### Head: Keybind
##

#source "$THE_SYS_PROFILE_DIR_PATH/default/keybind.sh"
#source "$THE_SYS_PROFILE_DIR_PATH/default_enhance/keybind.sh"
source "$THE_SYS_PROFILE_DIR_PATH/main/keybind.sh"

##
### Tail: Keybind
################################################################################


################################################################################
### Head: Rule
##

#source "$THE_SYS_PROFILE_DIR_PATH/default/rule.sh"
source "$THE_SYS_PROFILE_DIR_PATH/main/rule.sh"

##
### Tail: Rule
################################################################################


################################################################################
### Head: Main
##

__main__ () {
	skel_run
}

__main__

##
### Tail: Main
################################################################################
